builder:
  build: ./
  stdin_open: true
  tty: true
  dockerfile: docker/Dockerfile.builder
  links:
    - ganache
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
  env_file:
    .env
  volumes:
    - "./build/original:/marblegame/original/build"
    - "./build/bank:/marblegame/bank/build"
    - "./build/metatransactions:/marblegame/metatransactions/build"
    - "./build/erc20:/marblegame/erc20/build"
    - "./build/auction:/marblegame/auction/build"
    - "./src/original/contracts:/marblegame/original/contracts"
    - "./src/original/deployments:/marblegame/original/deployments"
    - "./src/original/migrations:/marblegame/original/migrations"
    - "./src/original/test:/marblegame/original/test"
    - "./src/bank/contracts:/marblegame/bank/contracts"
    - "./src/bank/migrations:/marblegame/bank/migrations"
    - "./src/bank/test:/marblegame/bank/test"
    - "./src/metatransactions/contracts:/marblegame/metatransactions/contracts"
    - "./src/metatransactions/deployments:/marblegame/metatransactions/deployments"
    - "./src/metatransactions/migrations:/marblegame/metatransactions/migrations"
    - "./src/metatransactions/test:/marblegame/metatransactions/test"
    - "./src/erc20/contracts:/marblegame/erc20/contracts"
    - "./src/erc20/migrations:/marblegame/erc20/migrations"
    - "./src/auction/contracts:/marblegame/auction/contracts"
    - "./src/auction/migrations:/marblegame/auction/migrations"
    - "./src/auction/test:/marblegame/auction/test"
ganache:
  image: trufflesuite/ganache-cli:latest
  command: ganache -p 8545 -h 0.0.0.0 --mnemonic "${mnemonic}" --blockTime 0
  ports:
  - 8545:8545
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
